spring:
  flyway:
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        default_schema: foodcart

  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=foodcart
